### ISSUE TITLE
Can't send '£'

### ISSUE THREAD

**Issue by otaviokz** [pkyeck/socket.IO-objc#219]
My app works flawlessly with socket.IO-objc, whit one exception, I can't send the char '£' on any message. It's a big issue since it's an UK app. 

Basically, as soon as a user send a message containing a '£', the app receives a didDisconnect avent with the error:

"Error Domain=SocketIOError Code=-4 "The operation couldn’t be completed. (SocketIOError error -4.)"

Has anybody ever experienced it?

**Comment by longzhang** [comment]
How about  try to encode it by utf-8?

**Comment by otaviokz** [comment]
I apologise for opening this issue. The actual problem was in the server.
