### ISSUE TITLE
handshake failed ... Server returned status code 400, Error Domain=SocketIOError Code=-6

### ISSUE THREAD

**Issue by NyeinEiEiTun** [pkyeck/socket.IO-objc#231]
When I tried to send events to server, I got these errors. Does anyone know this problem. 
![screen shot 2017-03-03 at 5 45 21 pm](https://cloud.githubusercontent.com/assets/26161959/23546158/43413ce0-0039-11e7-8c5d-98edf6880ebb.png)

**Comment by pkyeck** [comment]
which version of socket.io are you using?

**Comment by NyeinEiEiTun** [comment]
for the server side? I think server side is using socket.io version 1+. Actually, server side wants me to use this version of socket.io library https://github.com/socketio/socket.io/. But for the client side, i still need to support ios 7. That's why I used objective-c library for socket.io.

**Comment by pkyeck** [comment]
this library only supports socket.io < 1.0

**Comment by NyeinEiEiTun** [comment]
i got it. Thanks :)

**Comment by Dhaval3110** [comment]
@pkyeck Is there any special reason to library not working with socket IO v 1.0?

**Comment by pkyeck** [comment]
@Dhaval3110 yep, socket.io 1.0+ was a complete rewrite and I didn't have the time to do all the adjustments needed for this lib to work with v1.
